name: Build Test Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install depondencies
      run: npm install
    - name: Start BackEnd
      run: npm run start-be &
    - name: Start FrontEnd 
      run: npm run start-fe &
    - name: Install Playwright Browsers
      run: npx playwright install  
    - name: Start UI tests
      run: npm run test:ui

  deploy_backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build_test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  deploy_frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: deploy_backend
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}